---
title: "PSM + DID"
---


```{r}
library(MatchIt)
library(data.table)
library(dplyr)
library(tidyr)
library(plm)
library(fixest)
library(zoo)
library(did)
library(lubridate)
library(googledrive)
library(ggplot2)
library(arrow)
library(stargazer)
library(lmtest)
```

```{r}
pre_psm <- read_parquet('../data/presence_in_both_periods.parquet')
pre_psm$log_age = log(pre_psm$age)
pre_psm <- pre_psm %>%
  filter(year %in% c(2019, 2020))
pre_psm$treatment <- as.factor(pre_psm$is_employed_has_disablity)
pre_psm
```

```{r}
full_data <- read_parquet('../data/panel_common_pre_psm_mean3_months_with_add_health_variables_no_outliers.parquet')
full_data$log_age = log(full_data$age)
#full_data <- full_data %>%
#  filter(year %in% c( 2019, 2020, 2021))

full_data <- full_data %>%
  filter(!is.na(period_relevance))
full_data
```



```{r}
boxplot(pre_psm$net_job)
```

```{r}
ggplot(pre_psm, aes(x = factor(is_employed_has_disablity), y = net_job)) +
  # Use geom_boxplot to create the plot
  geom_boxplot(alpha = 0.7, fill = "lightblue") + 
  
  # OPTIONAL: Add jitter points to see every single data point 
  # (This helps ensure you aren't missing density information)
  geom_jitter(width = 0.1, alpha = 0.2, color = "darkgrey") + 
  
  # Improve appearance
  labs(title = "Comparison of Score Distribution by Group",
       y = "Score Value",
       x = "Group Category") +
  theme_minimal()
```

```{r}
ggplot(pre_psm, aes(x = factor(is_employed_has_disablity), y = log(net_job + 1))) +
  # Use geom_boxplot to create the plot
  geom_boxplot(alpha = 0.7, fill = "lightblue") + 
  
  # OPTIONAL: Add jitter points to see every single data point 
  # (This helps ensure you aren't missing density information)
  geom_jitter(width = 0.1, alpha = 0.2, color = "darkgrey") + 
  
  # Improve appearance
  labs(title = "Comparison of Score Distribution by Group",
       y = "Score Value",
       x = "Group Category") +
  theme_minimal()
```


```{r}
model1 <- feols(
    net_job ~ is_employed_has_disablity | idind + year,
    cluster = ~idind,
    data = pre_psm
)
print(summary(model1))

print(confint(model1, level = 0.95))
```

```{r}
model2 <- feols(
    log(net_job + 1) ~ is_employed_has_disablity | idind + year,
    cluster = ~idind,
    data = pre_psm
)
print(summary(model2))

print(confint(model2, level = 0.90))
```

```{r}
model3 <- feols(
    log(net_job + 1) ~ i(period_relevance, is_employed_has_disablity, ref = -1) | idind + year,
    cluster = ~idind,
    data = full_data
)
print(summary(model3))

print(confint(model3, level = 0.95))
```

```{r}
model4 <- feols(
    net_job ~ i(period_relevance, is_employed_has_disablity, ref = -1) | idind + year,
    cluster = ~idind,
    data = full_data
)
print(summary(model4))

print(confint(model4, level = 0.95))
```
```{r}
etable(model1, model2, order = "f", drop = "Int")
```

```{r}
etable(model3, model4, order = "f", drop = "Int")
```

```{r}
coefplot(model3)
```

```{r}
coefplot(model4)
```


```{r}
model4 <- feols(
    log(net_job + 1) ~ i(period_relevance, is_employed_has_disablity, ref = -1) + disability_class_first_group| idind + year,
    cluster = ~idind,
    data = full_data
)
print(summary(model4))

print(confint(model4, level = 0.95))
```



```{r}
psm <- matchit(is_employed_has_disablity ~ log_age + is_female +
                 educ_level_school_or_less + educ_level_common +
                 educ_level_higher + educ_level_university + is_married + 
                 chronic_lung + chronic_liver + chronic_kidney + 
                 chronic_stomach + chronic_spinal + disease_neuro + 
                 disease_eye + allegies,
                  data = full_data,
                  #method = "full",
                  #distance = "mahalanobis",
                  #distance = "glm",
                  #exact = ~log_age
               )
print(summary(psm, un = FALSE))
```


```{r}
plot(psm, type = "jitter", interactive = FALSE)
```


```{r}
plot(psm, type = "density", interactive = FALSE,
     which.xs = ~log_age + is_female +
                 educ_level_school_or_less + educ_level_common +
                 educ_level_higher + educ_level_university + is_married + 
                 chronic_lung + chronic_liver + chronic_kidney + 
                 chronic_stomach + chronic_spinal + disease_neuro + 
                 disease_eye + allegies)
```


```{r}
plot(summary(psm))
```


```{r}
m.data <- match_data(psm)
m.data
```


```{r}
write_parquet(m.data, '../data/panel_common_post_psm_full_mean3_months_with_add_health_variables_no_outliers.parquet')
```


```{r}
model5 <- feols(
    net_job ~ is_employed_has_disablity | idind + year,
    cluster = ~idind,
    data = m.data
)
print(summary(model5))
```

```{r}
model6 <- feols(
    log(net_job + 1) ~ is_employed_has_disablity | idind + year,
    cluster = ~idind,
    data = m.data
)
print(summary(model6))
```


```{r}
model4 <- feols(
    j60 ~ is_employed_has_disablity | idind + year,
    cluster = ~idind,
    data = m.data
)
print(summary(model4))
```


```{r}
data_plm <- pdata.frame(m.data, index = c("idind", "year"))

# Transform to plm
agg_did_model <- plm(
    net_job ~ is_employed_has_disablity,
    effect = "twoways",  # equivalent to | store + period
    #model = "withdevtools::install_github('sipemu/eventstudy')in",
    index = c("idind", "year"),
    data = data_plm
)

# For clustered standard errors at store level
summary(agg_did_model, vcov = vcovHC(agg_did_model, method = "arellano", type = "HC1", cluster = "group"))
```


```{r}
vcov_clustered <- vcovHC(agg_did_model, method = "arellano", type = "HC1", cluster = "group")
confint(agg_did_model, vcov. = vcov_clustered, level = 0.95)
```


```{r}
library(lmtest)
coeftest_result <- coeftest(agg_did_model, vcov. = vcov_clustered)

ci_coeftest <- confint(coeftest_result, level = 0.95)
print(ci_coeftest)
```

```{r}
event_data <- read_parquet('../data/panel_common_pre_psm_3last_months.parquet')
event_data$log_age = log(event_data$age)
event_data <- event_data %>%
  filter(year %in% c(2017, 2018, 2019, 2020, 2021))
event_data
```

```{r}
psm <- matchit(is_employed_has_disablity ~ log_age + is_female +
                 educ_level_school_or_less + educ_level_common +
                 educ_level_higher + educ_level_university + is_married,
                  data = event_data,
                  #method = "full",
                  #distance = "mahalanobis",
                  #distance = "glm",
                  exact = ~log_age
               )
print(summary(psm, un = FALSE))
```

```{r}
m.data <- match_data(psm)
m.data
```


```{r}
event_study_model <- feols(
    net_job ~ i(period_relevance, is_employed_has_disablity, ref = -1) | idind + year,
    cluster = ~idind,
    data = event_data
)

print(summary(event_study_model))
```


```{r}
event_study_model <- feols(
    net_job ~ i(period_relevance, is_employed_has_disablity, ref = -1) | idind + year,
    cluster = ~idind,
    data = m.data
)

print(summary(event_study_model))
```


# plm


```{r}
data_plm <- pdata.frame(pre_psm, index = c("idind", "year"))

# Transform to plm
agg_did_model <- plm(
    net_job ~ is_employed_has_disablity,
    effect = "twoways",  # equivalent to | store + period
    #model = "withdevtools::install_github('sipemu/eventstudy')in",
    index = c("idind", "year"),
    data = data_plm
)

# For clustered standard errors at store level
summary(agg_did_model, vcov = vcovHC(agg_did_model, method = "arellano", type = "HC1", cluster = "group"))
```

```{r}

coeftest_result <- coeftest(agg_did_model, vcov. = vcov_clustered)
print(confint(coeftest_result, level = 0.95))
```

```{r}
data_plm <- pdata.frame(pre_psm, index = c("idind", "year"))

# Transform to plm
agg_did_model <- plm(
    j60 ~ is_employed_has_disablity,
    effect = "twoways",  # equivalent to | store + period
    #model = "withdevtools::install_github('sipemu/eventstudy')in",
    index = c("idind", "year"),
    data = data_plm
)

# For clustered standard errors at store level
summary(agg_did_model, vcov = vcovHC(agg_did_model, method = "arellano", type = "HC1", cluster = "group"))
```




```{r}
m.data
```


```{r}
library("MatchIt")
data("lalonde", package = "MatchIt")
lalonde
```


```{r}
#1:1 NN matching w/ replacement on a logistic regression PS
m.out <- matchit(treat ~ age + educ + race + married + 
                   nodegree + re74 + re75, data = lalonde,
                 replace = TRUE)
m.out
```


```{r}
print(summary(m.out, addlvariables = ~ I(age^2) + I(re74==0) + 
          I(re75==0) + educ:race))
```


```{r}
m.sum <- summary(m.out, addlvariables = ~ I(age^2) + I(re74==0) + 
                   I(re75==0) + educ:race)
plot(m.sum, var.order = "unmatched")
```


```{r}
plot(m.out, type = "qq", which.xs = ~age + nodegree + re74)
```


```{r}
plot(m.out, type = "ecdf", which.xs = ~educ + married + re75)
```


```{r}
plot(m.out, type = "density", which.xs = ~age + educ + race)
```


```{r}
s.out <- matchit(treat ~ age + educ + race + married + 
                   nodegree + re74 + re75, data = lalonde,
                 method = "subclass", subclass = 4)
s.out
```


```{r}
print(summary(s.out))
```


```{r}
s <- summary(s.out, subclass = TRUE)
plot(s, var.order = "unmatched", abs = FALSE)
```


```{r}
plot(s.out, type = "density", which.xs = ~educ + married + re75,
     subclass = 1)
```


```{r}
library("cobalt")
```


```{r}
bal.tab(m.out, un = TRUE, stats = c("m", "v", "ks"))
```


```{r}
m.out2 <- matchit(treat ~ age + educ + race + married + 
                   nodegree + re74 + re75, data = lalonde)

#Balance on covariates after full and NN matching
bal.tab(treat ~ age + educ + race + married + 
          nodegree + re74 + re75, data = lalonde, 
        un = TRUE, weights = list(full = m.out, nn = m.out2))
```


```{r}
love.plot(m.out, binary = "std")
```


```{r}
love.plot(m.out, stats = c("m", "ks"), poly = 2, abs = TRUE,
          weights = list(nn = m.out2),
          drop.distance = TRUE, thresholds = c(m = .1),
          var.order = "unadjusted", binary = "std",
          shapes = c("circle filled", "triangle", "square"), 
          colors = c("red", "blue", "darkgreen"),
          sample.names = c("Original", "Full Matching", "NN Matching"),
          position = "bottom")
```


```{r}
gen_X <- function(n) {
  X <- matrix(rnorm(9 * n), nrow = n, ncol = 9)
  X[,5] <- as.numeric(X[,5] < .5)
  X
}

#~20% treated
gen_A <- function(X) {
  LP_A <- - 1.2 + log(2)*X[,1] - log(1.5)*X[,2] + log(2)*X[,4] - log(2.4)*X[,5] + log(2)*X[,7] - log(1.5)*X[,8]
  P_A <- plogis(LP_A)
  rbinom(nrow(X), 1, P_A)
}

# Continuous outcome
gen_Y_C <- function(A, X) {
  2*A + 2*X[,1] + 2*X[,2] + 2*X[,3] + 1*X[,4] + 2*X[,5] + 1*X[,6] + rnorm(length(A), 0, 5)
}
#Conditional:
#  MD: 2
#Marginal:
#  MD: 2

# Binary outcome
gen_Y_B <- function(A, X) {
  LP_B <- -2 + log(2.4)*A + log(2)*X[,1] + log(2)*X[,2] + log(2)*X[,3] + log(1.5)*X[,4] + log(2.4)*X[,5] + log(1.5)*X[,6]
  P_B <- plogis(LP_B)
  rbinom(length(A), 1, P_B)
}
#Conditional:
#  OR:   2.4
#  logOR: .875
#Marginal:
#  RD:    .144
#  RR:   1.54
#  logRR: .433
#  OR:   1.92
#  logOR  .655

# Survival outcome
gen_Y_S <- function(A, X) {
  LP_S <- -2 + log(2.4)*A + log(2)*X[,1] + log(2)*X[,2] + log(2)*X[,3] + log(1.5)*X[,4] + log(2.4)*X[,5] + log(1.5)*X[,6]
  sqrt(-log(runif(length(A)))*2e4*exp(-LP_S))
}
#Conditional:
#  HR:   2.4
#  logHR: .875
#Marginal:
#  HR:   1.57
#  logHR: .452

set.seed(19599)

n <- 2000
X <- gen_X(n)
A <- gen_A(X)

Y_C <- gen_Y_C(A, X)
Y_B <- gen_Y_B(A, X)
Y_S <- gen_Y_S(A, X)

d <- data.frame(A, X, Y_C, Y_B, Y_S)
d
```


```{r}
library("MatchIt")
library("marginaleffects")
```


```{r}
mV <- matchit(A ~ X1 + X2 + X3 + X4 + X5 + 
                X6 + X7 + X8 + X9,
              data = d,
              ratio = 2,
              max.controls = 4)
mV
```


```{r}
md <- match_data(mV)

head(md)
```


```{r}
fit1 <- lm(Y_C ~ A * (X1 + X2 + X3 + X4 + X5 + 
                        X6 + X7 + X8 + X9),
           data = md,
           weights = weights)
```


```{r}
avg_comparisons(fit1,
                variables = "A",
                vcov = ~subclass,
                newdata = subset(A == 1))
```


```{r}
avg_comparisons(fit1,
                variables = "A",
                vcov = ~subclass,
                newdata = subset(A == 1))
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

